categories: Categories
search: Search
tags: Tags
tagcloud: Tag Cloud
tweets: Tweets
prev: Prev
next: Next
comment: Comments
archive_a: Archives
archive_b: "Archives: %s"
page: Page %d
recent_posts: Recent Posts
newer: Newer
older: Older
share: Share
powered_by: Powered by %s
theme: Theme - %s
rss_feed: RSS Feed
category: Category
tag: Tag
site_visitors: Visitors
page_views: Views
friends: Friends

post:
  word_count: Word count
  read_time: Reading time
  minutes: min
  reward: Donate
  sticky: Sticky
  copyright_title: Copyright
  copyright_content: 版权所有属于未央。对于商业转载，请联系作者(邮箱: sheensong@163.com)以获取授权。 对于非商业转载，请注明出处。

lock:
  lock_info: Please enter password
  lock_error: Incorrect password, please try again
  confirm_text: Ok
  cancel_text: Cancel